export let filters = {
  billType:value=>{
    switch (value){
      case 0:
        value = [
          {
            id:'',
            name:'不限'
          },
          {
            id:'201',
            name:'境内差旅报销'
          },
          {
            id:'202',
            name:'主办会议报销'
          },
          {
            id:'203',
            name:'业务招待报销'
          },
          {
            id:'204',
            name:'其他费用报销'
          },
          {
            id:'205',
            name:'子女医药费报销'
          },
          {
            id:'206',
            name:'专项费用报销'
          },
          {
            id:'207',
            name:'信息费用报销'
          }
        ];
        break;
      case 1:
        value = [
          {
            id:'',
            name:'全部'
          },
          {
            id:'001',
            name:'已保存'
          },
          {
            id:'002',
            name:'审批中'
          },
          {
            id:'003',
            name:'审批拒绝'
          },
          {
            id:'004',
            name:'审批通过'
          },
          {
            id:'005',
            name:'已作废'
          },
          {
            id:'006',
            name:'已过账'
          },
          {
            id:'007',
            name:'过账失败'
          },
          {
            id:'008',
            name:'已支付'
          },
          {
            id:'009',
            name:'支付失败'
          },
          {
            id:'010',
            name:'已结算'
          },
          {
            id:'011',
            name:'结算失败'
          },
          {
            id:'000',
            name:'核定中'
          }
        ]
    }
    return value;
  }
}
